Vagrant.configure('2') do |config|
  config.vm.hostname              = 'ubuntu1404-fluentd'
  config.vm.provider :digital_ocean do |provider, override|
    provider.client_id            = 'YOUR_CLIENT_ID'
    provider.api_key              = 'YOUR_API_KEY'
    provider.ssh_key_name         = 'YOUR_SSH_KEY_NAME'
    provider.token                = 'YOUR_TOKEN'

    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box               = 'digital_ocean'
    override.vm.box_url           = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    provider.image                = 'Ubuntu 14.04 x64'
    provider.region               = 'sgp1'
    provider.size                 = '512MB'
#    provider.ca_path              = '/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt'
  end

  config.vm.provision :shell, :inline => <<-EOT
    apt-get update
    apt-get install -y ruby ruby-dev make g++ libxslt-dev libxml2-dev
    gem install fluentd --no-ri --no-rdoc
  EOT

end
